### ISSUE TITLE
error when batch geocoding more than max number of results

### ISSUE THREAD

**Issue by wilsaj** [Esri/geoservices-js#89]
Looks like the geocode service returns a max of 1000 results, silently discarding any additional queries. This is might be variable, but can be queried from the geocode service? https://developers.arcgis.com/rest/geocode/api-reference/geocoding-geocode-addresses.htm#GUID-FB22981C-FDC9-464D-9279-946EA859DC2B 

However it's determined, `batch()` should probably should throw an error when trying to queue up more than the limit rather than silently dropping results.

**Comment by jgravois** [comment]
this is definitely dependent on the individual service properties.  rather than try to incorporate a metadata request it seems to me like it would be simplest (and sufficient) to just doc the limitation more clearly [here](https://github.com/Esri/geoservices-js/blob/master/docs/Geocoding.md#batch-geocoding) and take the opportunity to suggest developers utilize something a lot closer to the `SuggestedBatchSize` than `MaxBatchSize`

does that sound okay to you?

**Comment by wilsaj** [comment]
Good point. Documenting would be enough.

Another idea: As far as I can tell, on `batch.run()` the number of results should equal the number of requested records (up to `MaxBatchSize`), so could throw an error if `results.length` < `records.length`
